twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        asset_base: '%kernel.project_dir%/public/assets'
        asset_img: '%kernel.project_dir%/public/assets/img'


