index:
    path: /
    controller: App\Controller\Authenticator::new

#Routes for User
users:
    path: /users
    controller: App\Controller\User::index

create_user:
    path: /create_user
    controller: App\Controller\User::new

edit_user:
    path: /edit_user/{id}
    controller: App\Controller\User::edit

remove_user:
    path: /remove_user/{id}
    controller: App\Controller\User::remove

#Routes for Customer
customers:
    path: /customers
    controller: App\Controller\Customer::index

create_customer:
    path: /create_customer
    controller: App\Controller\Customer::new

edit_customer:
    path: /edit_customer/{id}
    controller: App\Controller\Customer::edit

remove_customer:
    path: /remove_customer/{id}
    controller: App\Controller\Customer::remove

#Routes for Loan
loans:
    path: /loans
    controller: App\Controller\Loan::index

create_loan:
    path: /create_loan
    controller: App\Controller\Loan::new

edit_loan:
    path: /edit_loan/{id}
    controller: App\Controller\Loan::edit

remove_loan:
    path: /remove_loan/{id}
    controller: App\Controller\Loan::remove